### ISSUE TITLE
can not use lbc

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [naver-ai/cgl_fairness#2]
![a6465ec272f0e89eb632dcddc7aa2a5](https://github.com/naver-ai/cgl_fairness/assets/84905965/0a51e256-0821-4ed2-92b0-f7e70224f174)
I see the tutuial using lbc.
And I tried this command:
```
python main.py --model resnet18 --method lbc \
    --dataset celeba \
    --version cgl \
    --sv 0.8
``` 
But I got this error below:
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/493bad68-1d52-454a-a6a7-580288ef7a3b)

Another question is that the arg `--iter` doesn't appear in `main.py` so  I wonder the usage of `--iter`.
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/b5fab79f-52fb-4029-b9d6-fc021e9ff8d0)
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/21eac39c-af26-407d-9d0d-1e41a8461de8)

**Comment by SanghyukChun** [comment]
Hello, please use Please use the `reweighting` option for using LBC. You can check the details here:
https://github.com/naver-ai/cgl_fairness/issues/1#issuecomment-1615617168

**Comment by sangwon-jung94** [comment]
Hi, I'm sorry for a typo. It is `iteration`, not `iter`. And the `iter` argument is used in trainer/rewieghting.py. It represents the number of iterations for outer update of eta in a minimax optimization.  

We modified our README as well. Thanks.

**Comment by Ethan-Chen-plus** [comment]
@sangwon79 @SanghyukChun Thanks! However there still exists another error:
```
Traceback (most recent call last):
  File "/data1/cgl_fairness/main.py", line 124, in <module>
    main()
  File "/data1/cgl_fairness/main.py", line 98, in main
    trainer_.train(train_loader, test_loader, args.epochs, writer=writer)
  File "/data1/cgl_fairness/trainer/reweighting.py", line 46, in train
    weight_set = self.debias_weights(Y_train, S_train, extended_multipliers, num_groups, num_classes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/cgl_fairness/trainer/reweighting.py", line 207, in debias_weights
    weights = w_matrix[sen_attrs, label]
              ~~~~~~~~^^^^^^^^^^^^^^^^^^
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

so I use this in reweighting.py:
```
sen_attrs = sen_attrs.to(w_matrix.device)
label = label.to(w_matrix.device)
weights = w_matrix[sen_attrs, label]

```

It makes it run, but the score keeps in a low degree:
![image](https://github.com/naver-ai/cgl_fairness/assets/84905965/05fe5103-9f5c-44ce-852d-49a6b2bb9b4b)

**Comment by sangwon-jung94** [comment]
Thanks again.
The first issue may be due to the difference in the version of Torch package. It works well in our setting.
We left out a  line of code in the process of publishing our code.
The first and second issues have been solved in the modified code. Please git pull again.

**Comment by Ethan-Chen-plus** [comment]
Thanks a lot! This has been solved.
